### ISSUE TITLE
I cannot generate a functional script to save 

### ISSUE THREAD

**Issue by paconaranjo** [0xC0000054/avif-format#2]
```
var doc = app.activeDocument;

var docName = doc.name.replace(/\.[^\.]+$/, '');
var avifName = decodeURI(doc.path) + "/" + docName + ".avif";

var idsave = charIDToTypeID("save");
    var desc60 = new ActionDescriptor();
    var idAs = charIDToTypeID("As  ");
        var desc61 = new ActionDescriptor();
        var idQlty = charIDToTypeID("Qlty");
        desc61.putInteger(idQlty, 95);
        var idavoneC = charIDToTypeID("av1C");
        var idchSu = charIDToTypeID("chSu");
        var idchStwo = charIDToTypeID("chS2");
        desc61.putEnumerated(idavoneC, idchSu, idchStwo);
        var idavoneS = charIDToTypeID("av1S");
        var idcoSp = charIDToTypeID("coSp");
        var idcsPtwo = charIDToTypeID("csP2");
        desc61.putEnumerated(idavoneS, idcoSp, idcsPtwo);
        var idavoneB = charIDToTypeID("av1B");
        var idimBd = charIDToTypeID("imBd");
        var idiBdzero = charIDToTypeID("iBd0");
        desc61.putEnumerated(idavoneB, idimBd, idiBdzero);
    var idfiveninesevenBoneEeightthreefourFoneBfourAoneEnineBFeightzerosevensixeightDAzeroDtwosevensixthree = stringIDToTypeID("597B1E83-4F1B-4A1E-9BF8-0768DA0D2763");
    desc60.putObject(idAs, idfiveninesevenBoneEeightthreefourFoneBfourAoneEnineBFeightzerosevensixeightDAzeroDtwosevensixthree, desc61);
    var idIn = charIDToTypeID("In  ");
    desc60.putPath(idIn, new File(avifName));
    var idDocI = charIDToTypeID("DocI");
    desc60.putInteger(idDocI, 182);
    var idCpy = charIDToTypeID("Cpy ");
    desc60.putBoolean(idCpy, true);
    var idLwCs = charIDToTypeID("LwCs");
    desc60.putBoolean(idLwCs, true);
executeAction(idsave, desc60, DialogModes.NO);
```

I think the problem lies here:
```
    var idfiveninesevenBoneEeightthreefourFoneBfourAoneEnineBFeightzerosevensixeightDAzeroDtwosevensixthree = stringIDToTypeID("597B1E83-4F1B-4A1E-9BF8-0768DA0D2763");
    desc60.putObject(idAs, idfiveninesevenBoneEeightthreefourFoneBfourAoneEnineBFeightzerosevensixeightDAzeroDtwosevensixthree, desc61);
```

If I generate the script it works for that session, but if I restart Photoshop the script doesn't work anymore, it generates corrupted images.

For example, in the case of WebP it works perfectly well.

```
var documento = app.activeDocument;
var nombre = documento.name.replace(/\.[^\.]+$/, '');
var nombreWebP = decodeURI(documento.path) + "/" + nombre + ".webp";
var guardar = charIDToTypeID( "save" );
    var paso1 = new ActionDescriptor();
    var como = charIDToTypeID( "As  " );
        var paso2 = new ActionDescriptor();
        var calidad = charIDToTypeID( "wrtq" );
        paso2.putInteger( calidad, 97 );
        var compresion = charIDToTypeID( "wrtc" );
        paso2.putInteger( compresion, 2 );
        var datosEXIF = charIDToTypeID( "wrte" );
        paso2.putBoolean( datosEXIF, false );
        var datosXMP = charIDToTypeID( "wrtx" );
        paso2.putBoolean( datosXMP, false );
        var datosPerfil = charIDToTypeID( "wrtp" );
        paso2.putBoolean( datosPerfil, false );
        var vistaPrevia = charIDToTypeID( "wrtl" );
        paso2.putBoolean( vistaPrevia, true );
    var identificadorGoogleWebPShop = stringIDToTypeID( "Google WebPShop" );
    paso1.putObject( como, identificadorGoogleWebPShop, paso2 );
    var en = charIDToTypeID( "In  " );
    paso1.putPath( en, new File(nombreWebP) );
executeAction( guardar, paso1, DialogModes.NO );
```

**Comment by 0xC0000054** [comment]
I do not have any experience with Photoshop automation scripts, so I have no idea where the issue could be.

Are you are trying to batch process 8-bits-per-channel images?

**Comment by paconaranjo** [comment]
Yes, is for 8 bit images.

I use [ScriptinglLstener Plug-in](https://helpx.adobe.com/photoshop/kb/downloadable-plugins-and-content.html) and [ExtendScript Toolkit](https://github.com/Adobe-CEP/CEP-Resources/tree/master/ExtendScript-Toolkit).

This is another simple example for a working JPEG script dor saving with some especifications:

**Comment by 0xC0000054** [comment]
Can you upload the AVIF file?

**Comment by paconaranjo** [comment]
[Sello.zip](https://github.com/0xC0000054/avif-format/files/7448157/Sello.zip)

**Comment by 0xC0000054** [comment]
That is a valid AVIF file, I was able to open it with Paint.NET.

The 'ftyp' box is present in the file.
I have noticed that libheif sometimes fails to find the 'ftyp' box in other AVIF files.

I will file a bug report in the libheif repository.

**Comment by paconaranjo** [comment]
I can’t open it again with Photoshop. That’s and other software, only a few like Paint.NET. But if I don’t use the script I can be able to view as a thumbnail in windows.

Many thanks.

**Comment by 0xC0000054** [comment]
> But if I don’t use the script I can be able to view as a thumbnail in windows.

That is extremely strange, there should be no difference from the settings in the save UI.
But Microsoft's AVIF support has plenty of other bugs.
The Windows thumbnails do not display transparency, lossless encoding shows distorted colors and probably other things that I have missed.

If you set Paint.NET as the default program for AVIF files it will take over the AVIF thumbnail rendering.

**Comment by 0xC0000054** [comment]
The file opening issue was due to a bug in the plug-in, it has been fixed for the next release.

My code was assuming that Photoshop set the file position to the start of the file before calling the plugin.
It turns out that plugins need to set the file position before reading the file.

**Comment by paconaranjo** [comment]
Is it normal that the text string for identification is so long in AVIF compared to WebP which is very simple?

```
var idAVIF = stringIDToTypeID("597B1E83-4F1B-4A1E-9BF8-0768DA0D2763");

var idGoogleWebPShop = stringIDToTypeID( "Google WebPShop" );
```

**Comment by 0xC0000054** [comment]
Adobe requires that string in the plug-in resources to be unique, I used an [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier).
I will change it to a shorter format that is similar to what WebP uses.

**Comment by 0xC0000054** [comment]
Released version 1.0.1, which includes the above mentioned changes.

**Comment by paconaranjo** [comment]
It woks better!!!

Now I can open it in other software, for example Windows Paint, but if I export it with the script I can't, but I can open it in Photoshop again.

For some strange reason it does not save the same.

**Comment by 0xC0000054** [comment]
> For some strange reason it does not save the same.

What do you mean?

I had to update the `idAvif` value to match the new identifier, but the script appears to work fine.

**Comment by paconaranjo** [comment]
In a few days I'll be back from my trip and I'll send you a video with the problem... It must be something insignificant.

**Comment by paconaranjo** [comment]
Well, now is working fine, I don't know why. But thanks for everything, If I found another bug I tell you.
