### ISSUE TITLE
CDEF filter

### ISSUE THREAD

**Issue by Uch1haOb1to** [0xC0000054/avif-format#3]
Can you disable CDEF filter? Or, for example, make a checkbox to disable it?
CDEF filter strongly averages the colors of the image with strong compression and at the same time does not give a noticeable gain in quality. I think it makes no sense in the context of avif, since images do not compress as much as video, and with weak compression, there is no sense from the CDEF filter, it only harms by averaging colors.

**Comment by 0xC0000054** [comment]
I do not have an easy way to disable it, I would have to patch libheif to add that option to its AOM encoder interface.

**Comment by 0xC0000054** [comment]
I filed an issue in the libheif repository about extending the AOM encoder to allow any encoder option to be set.
https://github.com/strukturag/libheif/issues/596

Do you have an example image that shows the CDEF color differences?
I added the CDEF option to my Paint.,NET AVIF plugin as a test, and I did not notice any color differences in the preview image.

**Comment by Uch1haOb1to** [comment]
Thanks, I was about to open an issue in libheif myself, but you beat me to it.
The problem is visible when comparing avif with webp and jpg and the original image, not visible in all images.
I'll try to pick up images, but a little later. The first time I saw such a problem was when encoding a video with libaom, when encoding a recording of a game. I can attach these samples as I can't do avif with CDEF disabled anyway.

**Comment by 0xC0000054** [comment]
I just submitted a PR to enable lossless compression for alpha image in the libheif AOM encoder.
Adding a setting to disable CDEF is the next change I will be working on.

**Comment by Uch1haOb1to** [comment]
Now I'm looking, maybe it's not cdef, it's just that av1 itself changes colors. Webp and avif both have their colors changed, while the jpeg has the same colors as the original.
https://drive.google.com/drive/folders/1vE3RslvK_446C-SrGVQKijlONG3I3tWJ?usp=sharing

**Comment by 0xC0000054** [comment]
> it's just that av1 itself changes colors. Webp and avif both have their colors changed, while the jpeg has the same colors as the original.

That would make sense, each format uses its own lossy compression algorithm.

> But access to the aom settings, of course, will not be superfluous.

Some of the images in the AOM [test file repository](https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles) were created with CDEF disabled (e.g. ` hato.profile0.8bpc.yuv420.no-cdef.avif `), so it probably cannot hurt to offer that option.

As far as the other advanced options go, the only ones I have looked at are the encoder tiling options.
These options allow the encoder to split the image into a number of horizontal and vertical tiles, which can improve the encoder's ability to use multiple threads.

**Comment by Uch1haOb1to** [comment]
> can improve the encoder's ability to use multiple threads

I would not divide the picture into tiles smaller than 512x512 (it turns out four 128px SB), so as not to lose quality. Accordingly, small pictures in any case cannot be encoded on a large number of streams.
Large pictures already use many threads with the default row multithreading option enabled (row-mt), with my ryzen 5 5600U this is enough.
> As far as the other advanced options go, the only ones I have looked at are the encoder tiling options

I would like to be able to disable all deblocking filters, they can noticeably blur the picture.

**Comment by 0xC0000054** [comment]
> I would like to be able to disable all deblocking filters, they can noticeably blur the picture.

I am not sure if AV1 allows its deblocking filter to be disabled, I could not find any reference to it in the encoder options list.
The CDEF and loop restoration filters can be disabled.
While researching the CDEF option I found a technical blog post with a lot of information about the AVIF image compression: https://evilmartians.com/chronicles/decoding-avif-deep-dive-with-cats-and-imgproxy

> I would not divide the picture into tiles smaller than 512x512 (it turns out four 128px SB), so as not to lose quality. Accordingly, small pictures in any case cannot be encoded on a large number of streams.

I agree, my Paint,NET plugin does not use tiles for images smaller than 512x512.
AVIF supports two different tiling methods:

The first method is the one that I mentioned in my previous post, suggesting a tile count to the AV1 encoder that it may choose to utilize when encoding the frame. This method provides no direct control over the size or total number of 'tiles'.

The second method is to use the 'image grid' feature of the AVIF file format, this feature was inherited from the HEIF format that AVIF was based on.  An image grid is a collection of smaller images that a decoder will combine to form a larger image.
This gives the application direct control over the total number and size of the 'tiles', and it can also massively reduce the AOM encoder memory usage (memory usage was the main reason I implemented it in my Paint.NET plugin). 

Unfortunately, libheif does not support creating an image grid.

**Comment by Uch1haOb1to** [comment]
> This gives the application direct control over the total number and size of the 'tiles'

On the other hand, you need to write logic that will control this. For the grid to dock with the SB, as is now the case when using tiles.
> but the next version will

Okay, I'm waiting for the next version. It turns out you don’t even need to go deep into the aom parameters

**Comment by 0xC0000054** [comment]
Relesed version 1.0.2, which includes the AOM_USAGE_ALL_INTRA  change.
