### ISSUE TITLE
v1.0.2 does not work

### ISSUE THREAD

**Issue by Uch1haOb1to** [0xC0000054/avif-format#4]
Clicking the OK button gives an error. Does not depend on the selected encoding options.
![Oshibka_avif](https://user-images.githubusercontent.com/48291786/154807332-c5cbcf98-150b-4c17-b471-ed5a4145a6e8.png)
Photoshop 22.0.1

**Comment by StigNygaard** [comment]
I get same error with Photoshop 22.5.6.
![image](https://user-images.githubusercontent.com/5936108/154805718-3aed4266-c4cd-415a-a4d8-565aaf22b30e.png)

If options makes a difference, this was mine:
![image](https://user-images.githubusercontent.com/5936108/154805699-1619ae6b-352f-4a6e-a20a-886094d0b9c8.png)

**Comment by 0xC0000054** [comment]
Fixed in version 1.0.3.

**Comment by StigNygaard** [comment]
Thanks. Can confirm 1.0.3 works on my PCs, including "my other" which in the meantime was updated to Windows 11 Professional.
BTW, you might want to update your README.md (and Readme.txt in release zip) to include Windows 11 in "System Requirements", unless there's a special reason not to include windows version 11.
